/* Catalog tree: category → brand/item family → variant (flavor/style) → pack size.
   Pack prices are per pack, by warehouse. variant.only limits which packs a variant comes in;
   variant.delta shifts the pack price for that variant. Flattened into window.QB_ITEMS below. */
window.QB_STORES=[{key:'costco',name:'Costco'},{key:'bjs',name:"BJ's"},{key:'sams',name:"Sam's Club"},{key:'amazon',name:'Amazon'}];
window.QB_CATEGORIES=[
  {id:'drinks',name:'Drinks'},{id:'food',name:'Food'},{id:'catering',name:'Catering'},{id:'decor',name:'Décor'},
  {id:'paper',name:'Paper & Serving'},{id:'prizes',name:'Prizes & Giveaways'},{id:'addons',name:'Add-Ons'},{id:'staffing',name:'Staffing & Equipment Rental'}
];
const P=(costco,bjs,sams,amazon)=>({costco,bjs,sams,amazon});
window.QB_FAMILIES=[
  // ── Drinks
  {id:'coke',cat:'drinks',name:'Coca-Cola',unit:'can',perGuest:1.5,
   variants:[{id:'classic',name:'Classic'},{id:'cherry',name:'Cherry',only:['24'],delta:.6},{id:'zero',name:'Zero Sugar'},{id:'vanilla',name:'Vanilla',only:['12'],delta:.4}],
   packs:[{id:'12',label:'12 pack · 12 oz cans',per:12,prices:P(8.49,8.79,8.28,11.99)},
          {id:'24',label:'24 pack · 12 oz cans',per:24,prices:P(15.99,15.99,15.48,19.95)},
          {id:'35',label:'35 pack · 12 oz cans',per:35,prices:P(22.99,23.49,22.48,29.40)}]},
  {id:'pepsi',cat:'drinks',name:'Pepsi',unit:'can',perGuest:1.5,
   variants:[{id:'classic',name:'Classic'},{id:'diet',name:'Diet'},{id:'wild',name:'Wild Cherry',only:['24'],delta:.5}],
   packs:[{id:'24',label:'24 pack · 12 oz cans',per:24,prices:P(14.99,14.99,14.48,18.75)},
          {id:'36',label:'36 pack · 12 oz cans',per:36,prices:P(21.99,22.49,21.28,27.90)}]},
  {id:'lemonlime',cat:'drinks',name:'Lemon-lime soda',unit:'can',perGuest:1,
   variants:[{id:'regular',name:'Regular'},{id:'zero',name:'Zero sugar'}],
   packs:[{id:'24',label:'24 pack · 12 oz cans',per:24,prices:P(14.49,14.79,13.98,18.20)}]},
  {id:'water',cat:'drinks',name:'Bottled water',unit:'bottle',perGuest:2,
   variants:[{id:'purified',name:'Purified'},{id:'spring',name:'Spring',delta:.9}],
   packs:[{id:'24',label:'24 pack · 16.9 oz',per:24,prices:P(3.79,3.99,3.68,7.49)},
          {id:'40',label:'40 pack · 16.9 oz',per:40,prices:P(4.99,5.29,4.68,9.98)}]},
  {id:'juice',cat:'drinks',name:'Juice boxes',unit:'box',perGuest:1,
   variants:[{id:'apple',name:'Apple'},{id:'punch',name:'Fruit punch'},{id:'variety',name:'Variety pack',delta:.75}],
   packs:[{id:'40',label:'40 pack · 6.75 oz',per:40,prices:P(13.99,14.49,13.48,18.29)}]},
  {id:'sports',cat:'drinks',name:'Sports drink',unit:'bottle',perGuest:1,
   variants:[{id:'punch',name:'Fruit punch'},{id:'lemonlime',name:'Lemon-lime'},{id:'variety',name:'Variety',delta:1.25}],
   packs:[{id:'24-12',label:'24 pack · 12 oz bottles',per:24,prices:P(15.99,16.49,15.48,21.99)},
          {id:'18-20',label:'18 pack · 20 oz bottles',per:18,prices:P(17.99,18.49,17.28,23.40)}]},
  {id:'lemonade',cat:'drinks',name:'Lemonade, gallon jugs',unit:'gallon',perGuest:.08,
   variants:[{id:'classic',name:'Classic'},{id:'strawberry',name:'Strawberry',delta:.5}],
   packs:[{id:'2',label:'2 pack · 1 gallon',per:2,prices:P(7.49,6.99,7.28,null)}]},
  {id:'coffee',cat:'drinks',name:'Coffee service',unit:'serving',perGuest:.4,
   variants:[{id:'regular',name:'Regular roast'},{id:'decaf',name:'Decaf',delta:1.5}],
   packs:[{id:'100',label:'100 servings · 3 lb ground + cups',per:100,prices:P(26.99,28.49,27.44,34.10)}]},
  {id:'icedtea',cat:'drinks',name:'Iced tea, gallon jugs',unit:'gallon',perGuest:.08,
   variants:[{id:'classic',name:'Classic'},{id:'peach',name:'Peach',delta:.5}],
   packs:[{id:'2',label:'2 pack · 1 gallon',per:2,prices:P(7.29,6.79,6.98,null)}]},
  {id:'sparkling',cat:'drinks',name:'Sparkling water',unit:'can',perGuest:1,
   variants:[{id:'lime',name:'Lime'},{id:'blackcherry',name:'Black cherry'},{id:'plain',name:'Plain'}],
   packs:[{id:'24',label:'24 pack · 12 oz cans',per:24,prices:P(9.99,10.49,9.48,13.20)}]},
  {id:'cocoa',cat:'drinks',name:'Hot cocoa service',unit:'serving',perGuest:.3,
   variants:[{id:'classic',name:'Classic'},{id:'saltedcaramel',name:'Salted caramel',delta:1.5}],
   packs:[{id:'100',label:'100 servings · mix + cups',per:100,prices:P(24.99,26.49,23.98,29.10)}]},
  // ── Food
  {id:'hotdogs',cat:'food',name:'Beef hot dogs',unit:'hot dog',perGuest:1.5,
   variants:[{id:'regular',name:'Regular'},{id:'jumbo',name:'Jumbo 1/4 lb',delta:2.5}],
   packs:[{id:'12',label:'12 ct · 1.5 lb',per:12,prices:P(7.29,7.79,6.98,null)},
          {id:'32',label:'32 ct · 4 lb',per:32,prices:P(14.99,15.99,14.48,null)}]},
  {id:'buns',cat:'food',name:'Buns',unit:'bun',perGuest:1.5,
   variants:[{id:'hotdog',name:'Hot dog'},{id:'hamburger',name:'Hamburger',delta:.4}],
   packs:[{id:'24',label:'24 ct',per:24,prices:P(3.79,3.69,3.48,null)},
          {id:'48',label:'48 ct',per:48,prices:P(6.49,6.29,6.18,null)}]},
  {id:'burgers',cat:'food',name:'Burger patties',unit:'patty',perGuest:1,
   variants:[{id:'beef',name:'Beef, 1/4 lb'},{id:'veggie',name:'Veggie',delta:3}],
   packs:[{id:'24',label:'24 ct · frozen',per:24,prices:P(31.99,33.49,30.98,null)}]},
  {id:'chips',cat:'food',name:'Chips, single-serve',unit:'bag',perGuest:1,
   variants:[{id:'classic',name:'Classic mix'},{id:'cheesy',name:'Cheesy mix'},{id:'kids',name:'Kids favorites',delta:.75}],
   packs:[{id:'30',label:'30 bags',per:30,prices:P(14.99,15.49,14.28,19.99)},
          {id:'50',label:'50 bags',per:50,prices:P(22.99,23.99,21.98,29.50)}]},
  {id:'cookies',cat:'food',name:'Cookie tray',unit:'cookie',perGuest:1.5,
   variants:[{id:'assorted',name:'Assorted'},{id:'chocchip',name:'Chocolate chip'}],
   packs:[{id:'30',label:'30 ct',per:30,prices:P(7.99,8.49,7.68,null)},
          {id:'60',label:'60 ct',per:60,prices:P(12.99,13.99,12.98,null)}]},
  {id:'fruit',cat:'food',name:'Fruit tray',unit:'serving',perGuest:.5,
   variants:[{id:'std',name:''}],
   packs:[{id:'20',label:'Serves 20',per:20,prices:P(19.99,21.49,19.48,null)}]},
  {id:'popcorn',cat:'food',name:'Popcorn kit',unit:'serving',perGuest:1,
   variants:[{id:'butter',name:'Butter'},{id:'kettle',name:'Kettle corn',delta:2}],
   packs:[{id:'24',label:'24 servings · kernels + oil',per:24,prices:P(16.49,null,15.98,21.75)}]},
  {id:'watermelon',cat:'food',name:'Watermelon, sliced tray',unit:'serving',perGuest:.2,
   variants:[{id:'std',name:''}],
   packs:[{id:'20',label:'Serves 20',per:20,prices:P(18.99,null,17.48,null)}]},
  {id:'pretzels',cat:'food',name:'Pretzels, single-serve',unit:'bag',perGuest:1,
   variants:[{id:'original',name:'Original'},{id:'honeymustard',name:'Honey mustard',delta:.75}],
   packs:[{id:'30',label:'30 bags',per:30,prices:P(13.49,13.99,12.98,17.99)},
          {id:'50',label:'50 bags',per:50,prices:P(21.49,22.49,19.98,28.50)}]},
  {id:'icecream',cat:'food',name:'Ice cream novelties',unit:'bar',perGuest:1,
   variants:[{id:'assorted',name:'Assorted'},{id:'sandwiches',name:'Ice cream sandwiches',delta:1}],
   packs:[{id:'36',label:'36 ct · freezer case',per:36,prices:P(16.99,17.99,15.98,null)}]},
  // ── Catering
  {id:'tacobar',cat:'catering',name:'Taco bar package',unit:'plate',perGuest:1,
   variants:[{id:'chicken',name:'Chicken'},{id:'beef',name:'Beef',delta:20},{id:'both',name:'Chicken & beef',delta:35}],
   packs:[{id:'30',label:'Serves 30',per:30,prices:P(199.00,null,185.00,null)},
          {id:'50',label:'Serves 50',per:50,prices:P(325.00,null,299.00,null)}]},
  {id:'bbq',cat:'catering',name:'BBQ platter',unit:'plate',perGuest:1,
   variants:[{id:'pork',name:'Pulled pork & sides'},{id:'brisket',name:'Brisket & sides',delta:45}],
   packs:[{id:'30',label:'Serves 30',per:30,prices:P(229.00,245.00,219.00,null)},
          {id:'50',label:'Serves 50',per:50,prices:P(365.00,389.00,349.00,null)}]},
  {id:'pizza',cat:'catering',name:'Party pizza, 18"',unit:'pizza',perGuest:.13,
   variants:[{id:'cheese',name:'Cheese'},{id:'pepperoni',name:'Pepperoni',delta:1.5},{id:'combo',name:'Combination',delta:3}],
   packs:[{id:'4',label:'4 pies',per:4,prices:P(39.96,null,38.32,null)},
          {id:'6',label:'6 pies',per:6,prices:P(59.94,null,57.48,null)}]},
  {id:'sandwich',cat:'catering',name:'Deli sandwich platter',unit:'serving',perGuest:1,
   variants:[{id:'classic',name:'Classic assortment'},{id:'wraps',name:'Wraps',delta:6}],
   packs:[{id:'24',label:'Serves 24',per:24,prices:P(44.99,47.99,42.98,null)},
          {id:'48',label:'Serves 48',per:48,prices:P(84.99,89.99,79.98,null)}]},
  {id:'pastry',cat:'catering',name:'Breakfast pastries',unit:'pastry',perGuest:1,
   variants:[{id:'assorted',name:'Assorted'},{id:'muffins',name:'Muffins only'}],
   packs:[{id:'24',label:'24 ct',per:24,prices:P(12.99,13.99,12.48,null)},
          {id:'48',label:'48 ct',per:48,prices:P(21.99,23.49,20.98,null)}]},
  {id:'pastabar',cat:'catering',name:'Pasta bar package',unit:'plate',perGuest:1,
   variants:[{id:'marinara',name:'Marinara'},{id:'alfredo',name:'Alfredo',delta:20},{id:'both',name:'Marinara & alfredo',delta:35}],
   packs:[{id:'30',label:'Serves 30',per:30,prices:P(215.00,null,205.00,null)},
          {id:'50',label:'Serves 50',per:50,prices:P(349.00,null,329.00,null)}]},
  {id:'breakfast',cat:'catering',name:'Continental breakfast package',unit:'serving',perGuest:1,
   variants:[{id:'classic',name:'Classic'},{id:'deluxe',name:'Deluxe, hot items',delta:35}],
   packs:[{id:'20',label:'Serves 20',per:20,prices:P(89.99,94.99,84.98,null)},
          {id:'40',label:'Serves 40',per:40,prices:P(159.99,169.99,149.98,null)}]},
  // ── Décor
  {id:'balloons',cat:'decor',name:'Latex balloons',unit:'balloon',perGuest:2,
   variants:[{id:'assorted',name:'Assorted colors'},{id:'goldwhite',name:'Gold & white',delta:2},{id:'pastel',name:'Pastel',delta:1.5}],
   packs:[{id:'72',label:'72 ct',per:72,prices:P(10.99,null,9.98,9.49)},
          {id:'144',label:'144 ct',per:144,prices:P(18.99,null,17.48,15.99)}]},
  {id:'linens',cat:'decor',name:'Disposable table linens',unit:'linen',perGuest:.15,
   variants:[{id:'white',name:'White'},{id:'black',name:'Black'},{id:'kraft',name:'Kraft',delta:1}],
   packs:[{id:'6',label:'6 pack · 54x108',per:6,prices:P(13.49,14.29,12.98,16.99)},
          {id:'12',label:'12 pack · 54x108',per:12,prices:P(24.99,26.49,23.98,29.99)}]},
  {id:'lights',cat:'decor',name:'Outdoor string lights',unit:'strand',perGuest:0,
   variants:[{id:'warm',name:'Warm white, 48 ft'},{id:'cafe',name:'Café bulb, 24 ft',delta:-6}],
   packs:[{id:'2',label:'2 strands',per:2,prices:P(39.99,42.99,37.98,44.95)}]},
  {id:'center',cat:'decor',name:'Centerpiece kit',unit:'centerpiece',perGuest:.1,
   variants:[{id:'floral',name:'Floral + vase'},{id:'lantern',name:'Lantern + candle',delta:4}],
   packs:[{id:'6',label:'6 ct',per:6,prices:P(34.99,null,32.98,38.50)}]},
  {id:'signage',cat:'decor',name:'Banner & yard sign set',unit:'set',perGuest:0,
   variants:[{id:'generic',name:'Generic celebration'},{id:'custom',name:'Custom printed',delta:18}],
   packs:[{id:'1',label:'1 set',per:1,prices:P(null,null,22.98,24.99)}]},
  {id:'balloonarch',cat:'decor',name:'Balloon arch kit',unit:'kit',perGuest:0,
   variants:[{id:'goldwhite',name:'Gold & white',delta:5},{id:'pastel',name:'Pastel',delta:3},{id:'rainbow',name:'Rainbow'}],
   packs:[{id:'1',label:'1 kit · 8 ft arch',per:1,prices:P(34.99,null,32.98,29.99)}]},
  {id:'runners',cat:'decor',name:'Table runners',unit:'runner',perGuest:.1,
   variants:[{id:'white',name:'White'},{id:'black',name:'Black'},{id:'kraft',name:'Kraft',delta:1}],
   packs:[{id:'6',label:'6 pack',per:6,prices:P(9.99,10.49,8.98,12.99)},
          {id:'12',label:'12 pack',per:12,prices:P(17.99,18.99,16.48,22.99)}]},
  {id:'backdrop',cat:'decor',name:'Photo backdrop stand',unit:'set',perGuest:0,
   variants:[{id:'frame',name:'Adjustable frame only'},{id:'drape',name:'Frame + drape',delta:15}],
   packs:[{id:'1',label:'1 set',per:1,prices:P(49.99,null,46.98,54.99)}]},
  // ── Paper & Serving
  {id:'plates',cat:'paper',name:'Heavy-duty paper plates',unit:'plate',perGuest:2,
   variants:[{id:'10',name:'10 inch'},{id:'9',name:'9 inch',delta:-3}],
   packs:[{id:'100',label:'100 ct',per:100,prices:P(11.49,12.29,10.98,15.20)},
          {id:'200',label:'200 ct',per:200,prices:P(19.99,21.49,18.98,26.40)}]},
  {id:'cups',cat:'paper',name:'Plastic cups',unit:'cup',perGuest:2,
   variants:[{id:'18',name:'18 oz'},{id:'9',name:'9 oz',delta:-4}],
   packs:[{id:'120',label:'120 ct',per:120,prices:P(9.49,9.99,8.98,13.10)},
          {id:'240',label:'240 ct',per:240,prices:P(16.99,17.99,15.98,22.10)}]},
  {id:'cutlery',cat:'paper',name:'Cutlery kits',unit:'set',perGuest:1.5,
   variants:[{id:'std',name:'Fork, knife, spoon'}],
   packs:[{id:'180',label:'180 ct',per:180,prices:P(12.99,13.99,11.98,16.40)},
          {id:'360',label:'360 ct',per:360,prices:P(22.99,24.49,21.98,28.75)}]},
  {id:'napkins',cat:'paper',name:'Napkins, 2-ply',unit:'napkin',perGuest:3,
   variants:[{id:'white',name:'White'},{id:'colored',name:'Colored',delta:2}],
   packs:[{id:'500',label:'500 ct',per:500,prices:P(8.99,9.49,8.28,12.10)},
          {id:'1000',label:'1,000 ct',per:1000,prices:P(14.99,15.49,13.98,19.25)}]},
  {id:'chafing',cat:'paper',name:'Chafing dish set with fuel',unit:'set',perGuest:0,
   variants:[{id:'std',name:''}],
   packs:[{id:'4',label:'4 sets',per:4,prices:P(29.99,31.99,28.48,34.99)}]},
  {id:'utensils',cat:'paper',name:'Serving utensils',unit:'piece',perGuest:0,
   variants:[{id:'std',name:'Tongs, spoons, ladles'}],
   packs:[{id:'12',label:'12 piece',per:12,prices:P(18.49,null,17.48,21.99)}]},
  {id:'trays',cat:'paper',name:'Disposable serving trays',unit:'tray',perGuest:0,
   variants:[{id:'halfsize',name:'Foil, half-size'},{id:'fullsize',name:'Foil, full-size',delta:2}],
   packs:[{id:'10',label:'10 ct',per:10,prices:P(14.99,15.99,13.98,18.50)}]},
  {id:'skirting',cat:'paper',name:'Table skirting',unit:'roll',perGuest:0,
   variants:[{id:'white',name:'White'},{id:'black',name:'Black'}],
   packs:[{id:'1',label:'1 roll · 14 ft',per:1,prices:P(12.99,null,11.98,15.99)}]},
  // ── Prizes & Giveaways
  {id:'giftcards',cat:'prizes',name:'Gift cards',unit:'card',perGuest:0,
   variants:[{id:'25',name:'$25 value'},{id:'50',name:'$50 value',delta:100}],
   packs:[{id:'4',label:'4 cards',per:4,prices:P(100.00,100.00,100.00,100.00)}]},
  {id:'basket',cat:'prizes',name:'Raffle prize basket',unit:'basket',perGuest:0,
   variants:[{id:'mid',name:'Mid-tier'},{id:'premium',name:'Premium',delta:45}],
   packs:[{id:'1',label:'1 basket',per:1,prices:P(64.99,null,59.98,74.95)}]},
  {id:'tumblers',cat:'prizes',name:'Branded tumblers, 20 oz',unit:'tumbler',perGuest:.35,
   variants:[{id:'std',name:'Single-color print'},{id:'full',name:'Full-color print',delta:22}],
   packs:[{id:'12',label:'12 pack',per:12,prices:P(49.99,null,46.98,54.00)},
          {id:'24',label:'24 pack',per:24,prices:P(89.99,null,84.98,96.00)}]},
  {id:'goody',cat:'prizes',name:'Goody bag fillers',unit:'piece',perGuest:1,
   variants:[{id:'kids',name:'Kids assortment'},{id:'teen',name:'Teen assortment',delta:6}],
   packs:[{id:'100',label:'100 piece',per:100,prices:P(null,26.99,24.98,29.99)}]},
  {id:'grand',cat:'prizes',name:'Grand prize',unit:'prize',perGuest:0,
   variants:[{id:'speaker',name:'Bluetooth speaker'},{id:'tablet',name:'Tablet',delta:75}],
   packs:[{id:'1',label:'1 prize',per:1,prices:P(79.99,84.99,77.98,89.99)}]},
  {id:'medals',cat:'prizes',name:'Custom medals & ribbons',unit:'piece',perGuest:0,
   variants:[{id:'participation',name:'Participation'},{id:'placement',name:'1st/2nd/3rd set',delta:6}],
   packs:[{id:'25',label:'25 ct',per:25,prices:P(null,29.99,27.98,32.99)}]},
  {id:'raffle',cat:'prizes',name:'Raffle ticket roll & drum',unit:'set',perGuest:0,
   variants:[{id:'std',name:''}],
   packs:[{id:'1',label:'1 set · 2,000 tickets + drum',per:1,prices:P(19.99,null,18.48,22.99)}]},
  // ── Add-Ons
  {id:'photobooth',cat:'addons',name:'Photo booth kit',unit:'kit',perGuest:0,
   variants:[{id:'props',name:'Props + backdrop'},{id:'instant',name:'Props + instant camera',delta:70}],
   packs:[{id:'1',label:'1 kit',per:1,prices:P(null,null,49.98,54.99)}]},
  {id:'cottoncandy',cat:'addons',name:'Cotton candy supplies',unit:'serving',perGuest:.6,
   variants:[{id:'classic',name:'Classic flavors'},{id:'variety',name:'Variety flavors',delta:5}],
   packs:[{id:'100',label:'100 servings',per:100,prices:P(39.99,null,37.48,44.99)}]},
  {id:'facepaint',cat:'addons',name:'Face painting kit',unit:'kit',perGuest:0,
   variants:[{id:'std',name:'Professional grade'}],
   packs:[{id:'1',label:'1 kit',per:1,prices:P(null,null,34.98,39.99)}]},
  {id:'lawngames',cat:'addons',name:'Lawn game set',unit:'set',perGuest:0,
   variants:[{id:'4',name:'4 games'},{id:'giant',name:'Giant yard games',delta:35}],
   packs:[{id:'1',label:'1 set',per:4,prices:P(69.99,74.99,67.98,79.99)}]},
  {id:'ice',cat:'addons',name:'Ice, 20 lb bags',unit:'bag',perGuest:.08,
   variants:[{id:'std',name:''}],
   packs:[{id:'4',label:'4 bags',per:4,prices:P(11.96,12.76,10.96,null)},
          {id:'8',label:'8 bags',per:8,prices:P(23.92,25.52,21.92,null)}]},
  {id:'bouncehouse',cat:'addons',name:'Bounce house rental',unit:'day',perGuest:0,
   variants:[{id:'standard',name:'Standard 13x13'},{id:'combo',name:'Combo with slide',delta:150}],
   packs:[{id:'1',label:'Per day',per:1,flat:175.00}]},
  {id:'snowcone',cat:'addons',name:'Snow cone machine kit',unit:'kit',perGuest:0,
   variants:[{id:'classic',name:'Classic syrups'},{id:'tropical',name:'Tropical syrups',delta:5}],
   packs:[{id:'1',label:'1 kit · serves ~100',per:1,prices:P(null,null,44.98,49.99)}]},
  // ── Staffing & Equipment Rental (in-house rates)
  {id:'lead',cat:'staffing',name:'Event lead, on-site',unit:'hour',perGuest:0,
   variants:[{id:'std',name:''}],
   packs:[{id:'4',label:'4 hour block',per:4,flat:140.00},{id:'8',label:'8 hour block',per:8,flat:260.00}]},
  {id:'assistant',cat:'staffing',name:'Event assistant',unit:'hour',perGuest:0,
   variants:[{id:'std',name:''}],
   packs:[{id:'4',label:'4 hour block',per:4,flat:96.00},{id:'8',label:'8 hour block',per:8,flat:180.00}]},
  {id:'tables',cat:'staffing',name:'Folding table rental',unit:'table',perGuest:.12,
   variants:[{id:'6ft',name:'6 ft rectangle'},{id:'round',name:'60" round',delta:8}],
   packs:[{id:'4',label:'4 tables',per:4,flat:48.00},{id:'8',label:'8 tables',per:8,flat:88.00}]},
  {id:'chairs',cat:'staffing',name:'Folding chair rental',unit:'chair',perGuest:1,
   variants:[{id:'std',name:'White resin'}],
   packs:[{id:'20',label:'20 chairs',per:20,flat:70.00},{id:'40',label:'40 chairs',per:40,flat:130.00}]},
  {id:'tent',cat:'staffing',name:'Canopy tent rental',unit:'tent',perGuest:0,
   variants:[{id:'10x10',name:'10 x 10'},{id:'10x20',name:'10 x 20',delta:85}],
   packs:[{id:'1',label:'1 tent, per day',per:1,flat:125.00}]},
  {id:'pa',cat:'staffing',name:'PA system + mic rental',unit:'day',perGuest:0,
   variants:[{id:'std',name:''}],
   packs:[{id:'1',label:'Per day',per:1,flat:85.00}]}
];

// Flatten the tree into priced line-item records: id = family.variant.pack
window.QB_ITEMS=[];
window.QB_FAMILIES.forEach(f=>{
  f.variants.forEach(v=>{
    f.packs.forEach(p=>{
      if(v.only&&v.only.indexOf(p.id)<0) return;
      const d=v.delta||0;
      const prices={};
      window.QB_STORES.forEach(s=>{prices[s.key]=p.prices&&p.prices[s.key]!=null?+(p.prices[s.key]+d).toFixed(2):null;});
      const label=[f.name,v.name].filter(Boolean).join(' · ');
      window.QB_ITEMS.push({
        id:f.id+'.'+v.id+'.'+p.id,cat:f.cat,family:f.id,variant:v.id,pack:p.id,
        name:label+' — '+p.label,short:label,packLabel:p.label,
        unit:f.unit,per:p.per,perGuest:f.perGuest,prices,
        flat:p.flat!=null?+(p.flat+d).toFixed(2):null
      });
    });
  });
});
window.QB_SAMPLE=[
  {cat:'drinks',item:'coke.classic.35',packs:2},{cat:'drinks',item:'coke.cherry.24',packs:1},{cat:'drinks',item:'water.purified.40',packs:3},
  {cat:'food',item:'hotdogs.regular.32',packs:3},{cat:'food',item:'buns.hotdog.48',packs:2},{cat:'food',item:'chips.classic.30',packs:2},
  {cat:'paper',item:'plates.10.200',packs:1},{cat:'paper',item:'cups.18.240',packs:1},
  {cat:'decor',item:'balloons.assorted.144',packs:1},
  {cat:'prizes',item:'basket.mid.1',packs:2},
  {cat:'staffing',item:'tables.6ft.4',packs:2},{cat:'staffing',item:'tent.10x10.1',packs:1}
];
