window.CS_CATEGORIES = [
  {id:'all',label:'All events'},
  {id:'food',label:'Food & Beverage'},
  {id:'seasonal',label:'Seasonal'},
  {id:'holiday',label:'Holidays'},
  {id:'family',label:'Family'},
  {id:'social',label:'Social & Games'},
  {id:'community',label:'Community'},
  {id:'wellness',label:'Wellness'},
  {id:'pet',label:'Pet-Friendly'}
];

window.CS_PRICE_BANDS = [{id:'all',label:'All prices'},{id:'800',label:'$800'},{id:'1250',label:'$1,250'},{id:'1750',label:'$1,750'}];

window.CS_EVENTS = [
  {id:'trivia',title:'Trivia Night',cat:'Games & Social',tags:['social'],dur:'1–2 hours',price:1250,
   desc:'Hosted rounds, snacks and drinks, and prizes for the top three tables.',
   inc:['Assorted packaged snacks','Soda, water, and energy drinks','Television or display setup','Trivia game coordination','First, second, and third-place prizes','Setup and event support'],
   add:['Professional trivia host','Premium prize package','Themed decorations','Catered food as a vendor pass-through','DJ or upgraded sound','Event photographer']},
  {id:'bagel',title:'National Bagel Day Bar',cat:'Food & Beverage',tags:['food'],dur:'1–2 hours',price:1250,
   desc:'A full bagel and spread bar with cold brew, labels, and tabletop signage.',
   inc:['Plain, everything, cinnamon-raisin, blueberry, and gluten-free bagels','Multiple cream cheese flavors and dairy-free spread','Fruit, Nutella, avocado, peanut butter, and jam','Cold-brew coffee and ice','Toasters, bagel slicer, plates, cups, napkins, and utensils','Reusable food labels and tabletop signs'],
   add:['Hot coffee station','Fresh juice service','Pastry assortment','Premium floral décor','Custom branded cups','Event photographer']},
  {id:'valentines',title:"Valentine's Bouquet Bar",cat:'Holiday',tags:['holiday'],dur:'1–2 hours',price:800,
   desc:'Residents build and wrap their own bouquets at a styled flower bar.',
   inc:['Roses, lilies, sunflowers, filler flowers, and greenery','Rose-petal floor accents','Ribbon, twine, and bouquet-wrapping supplies','Custom postcards and envelopes','Flower-bar setup and presentation','On-site activity support'],
   add:['Premium vase upgrade','Chocolate or dessert station','Photo backdrop','Balloon installation','Live acoustic musician','Event photographer']},
  {id:'madness',title:'March Madness Watch Party',cat:'Sports & Social',tags:['social','seasonal'],dur:'1–2 hours',price:800,
   desc:'Game-day food, arcade basketball, and a bracket competition setup.',
   inc:['Cupcakes with basketball toppers','Ribs, pinwheels, wings, fruit, and hummus','Soda and serving supplies','Basketball tablecloths and decorations','Two-player arcade basketball game','Scoreboard whiteboard and competition setup'],
   add:['Large-screen television rental','Team-themed décor package','Premium winner prizes','Catered game-day food as a vendor pass-through','Sports photographer','Additional game stations']},
  {id:'waffle',title:'Build-Your-Own Waffle Bar',cat:'Food & Beverage',tags:['food','family'],dur:'Up to 1 hour',price:1250,
   desc:'A hot waffle station with sweet toppings, run start to finish.',
   inc:['Waffle mix and waffle-maker setup','Nutella, syrup, whipped cream, chocolate chips, and honey','Strawberries and blueberries','Peanut butter','Plates and napkins','Setup and basic event support'],
   add:['Additional waffle maker','Coffee or hot cocoa station','Savory waffle toppings','Fresh juice bar','Premium tabletop décor','Event attendant']},
  {id:'piday',title:'Pi Day Pizza Party',cat:'Food & Beverage',tags:['food'],dur:'Up to 1 hour',price:1250,
   desc:'Personal pizzas, themed setup, and a restaurant gift-card raffle.',
   inc:['Personal cheese pizzas','Personal pepperoni pizzas','Plates and napkins','Pizza-themed event setup','Restaurant gift-card raffle','Basic event support'],
   add:['Gluten-free pizza options','Dessert pies','Soda and beverage station','Pi Day trivia','Additional raffle prizes','Catered pizza as a vendor pass-through']},
  {id:'dog',title:'Dog Adoption & Pet Appreciation Day',cat:'Pet-Friendly',tags:['pet','community'],dur:'1–2 hours',price:800,
   desc:'Treat stations, gift bags, and a play area for resident pets.',
   inc:['Dog bowls and treat stations','Milk-Bone and Greenies treats','Portable dog playpen setup when needed','Pet gift bags','Waste-bag dispensers and poop bags','Dog leashes and take-home bowls'],
   add:['Local shelter or rescue coordination','Pet photographer','Dog treat vendor','Pet costume contest','Custom bandanas','Mobile grooming or training partner']},
  {id:'patio',title:'Patio Decorating Contest',cat:'Resident Contest',tags:['community'],dur:'Multi-day',price:1250,
   desc:'A multi-day resident contest with judging, prizes, and coordination.',
   inc:['Top-three resident prize package','Home-improvement gift cards','Garden-center gift cards','First-place garden-tool bonus','Watering can, plant ties, and plant tags','Contest organization and winner coordination'],
   add:['Printed voting materials','Online resident voting setup','Winner photography','Seasonal welcome signs','Additional honorable-mention prizes','Closing resident social']},
  {id:'fitness',title:'Resident Fitness Session',cat:'Wellness',tags:['wellness'],dur:'1 hour',price:800,
   desc:'A trainer-led session in your fitness center with hydration station.',
   inc:['One-hour personal trainer reservation','Gatorade','Bottled water','Basic workout-area setup','Resident check-in support','Vendor coordination'],
   add:['Second trainer or extended session','Yoga mats','Healthy snack station','Smoothie or juice vendor','Wellness giveaway bags','Fitness photographer'],
   note:'The trainer is a third-party pass-through service. Any vendor fee is billed to the property.'},
  {id:'market',title:'Community Farmers Market',cat:'Community Market',tags:['community','seasonal'],dur:'2–3 hours',price:1750,
   desc:'Tents, tables, signage, and layout for an on-site resident market.',
   inc:['Three 10-by-10 tents with weights','Three folding tables with fitted tablecloths','Reusable chalkboard vendor signs','Custom resident tote bags','Two picnic-table sets','Market layout, setup, and breakdown'],
   add:['Local vendor sourcing','Live acoustic music','Coffee or food truck','Additional tents and tables','Branded market signage','Event photographer']},
  {id:'donut',title:'National Donut Day',cat:'Food & Beverage',tags:['food'],dur:'Up to 1 hour',price:1250,
   desc:'Eight dozen donuts with coffee and milk service for a morning turnout.',
   inc:['Eight dozen glazed donuts','Individual milk cartons','Regular coffee','Decaffeinated coffee','Basic beverage setup','Serving and cleanup supplies'],
   add:['Specialty donut flavors','Mobile coffee cart','Custom branded napkins','Fruit and yogurt options','Balloon décor','Resident giveaway']},
  {id:'pool',title:'Community Pool Party',cat:'Seasonal',tags:['seasonal','family'],dur:'2–3 hours',price:1750,
   desc:'A full poolside cookout with shaved ice service for around 100 guests.',
   inc:['Hot dogs, burgers, chips, and pizza','Gluten-free pizza option','Fruit and vegetable trays','Soda and serving cups','Kona Ice service for ~100 guests','Additional folding tables','Poolside setup and event support'],
   add:['Professional DJ','Pool games and competitions','Photo booth','Premium décor','Event photographer','Additional catering as a vendor pass-through'],
   note:'Kona Ice and any outside catering are third-party pass-through services.'},
  {id:'icecream',title:'National Ice Cream Day',cat:'Food & Beverage',tags:['food','family'],dur:'Up to 1 hour',price:1250,
   desc:'A build-your-own sundae bar with cones, syrups, and toppings.',
   inc:['Vanilla, chocolate, cookies-and-cream, and specialty flavors','Ice cream cones','Topping bowls','Ice cream syrups','Cherries and assorted toppings','Serving setup and cleanup'],
   add:['Ice cream cart','Dairy-free options','Sundae competition','Custom cups and spoons','Balloon décor','Photo backdrop']},
  {id:'school',title:'Back-to-School Supply Event',cat:'Community Support',tags:['community','family'],dur:'1–2 hours',price:1750,
   desc:'Assembled supply bags and backpack giveaways for resident families.',
   inc:['Colored pencils, pencils, crayons, erasers, glue, and rulers','Supply bags for ~100 recipients','Five backpack giveaways','Bag assembly and distribution setup','Welcome and pickup area','On-site event support'],
   add:['Additional backpacks','Notebooks and folders','Snack station','School-themed décor','Local sponsor support','Family photo area']},
  {id:'fall',title:'Fall Festival',cat:'Seasonal',tags:['seasonal','family'],dur:'1–2 hours',price:1250,
   desc:'Caramel apples, cider, and seasonal styling across your common area.',
   inc:['Assorted caramel apples','Pumpkin pies and apple cider','Pumpkin donuts','Fall tablecloths and serving tables','Seasonal plates, cups, and utensils','Fall signs and decorations'],
   add:['Pumpkin decorating station','Live acoustic music','Hay-bale photo area','Coffee or cocoa bar','Kids activity station','Event photographer']},
  {id:'coffee',title:'National Coffee Day',cat:'Food & Beverage',tags:['food'],dur:'Up to 1 hour',price:1250,
   desc:'Local roasted coffee service with seasonal syrups and to-go cups.',
   inc:['Combination carafe and single-serve coffee maker','Local roasted coffee','Coffee pods','Pumpkin-spice syrup','To-go cups with lids and napkins','Apple cider option'],
   add:['Mobile barista service','Pastry assortment','Alternative milks','Custom branded cups','Seasonal décor','Resident coffee giveaway']},
  {id:'halloween',title:'Halloween Costume Contest & Photo Area',cat:'Holiday',tags:['holiday'],dur:'1–2 hours',price:800,
   desc:'A styled photo area plus a judged costume contest with gift-card prizes.',
   inc:['Halloween photo backdrop and adjustable stand','Hay-bale photo-area styling','Treat bags and indoor decorations','Assorted bulk candy','Three costume-contest gift-card prizes','Contest and photo-area coordination'],
   add:['Professional photographer','DJ and dance area','Additional costume categories','Fog or lighting effects','Catered desserts as a vendor pass-through','Premium balloon installation']},
  {id:'pumpkin',title:'Pumpkin Decorating & Fall Hangout',cat:'Seasonal',tags:['seasonal','family'],dur:'1–2 hours',price:1250,
   desc:'Around 80 pumpkins, craft supplies, and cider for an all-ages afternoon.',
   inc:['~80 small pumpkins','Acrylic paint markers','Adhesive googly eyes','Pumpkin decorating stickers','Apple cider, pumpkin donuts, and pies','Hot cups, napkins, setup, and cleanup'],
   add:['Additional pumpkins','Premium craft supplies','Fall photo backdrop','Coffee or cocoa station','Resident prize package','Event photographer']},
  {id:'dessert',title:'Halloween Dessert Bar',cat:'Holiday',tags:['holiday','food'],dur:'1–2 hours',price:1250,
   desc:'A seasonal dessert table with themed décor and centerpieces.',
   inc:['Halloween-themed Bundtinis','Pumpkin pies and frosted cookies','Halloween Oreos','Apple cider and pumpkin donuts','Serving tables and Halloween tablecloths','Seasonal centerpieces and hanging decorations'],
   add:['Hot cocoa or coffee bar','Custom dessert signage','Premium backdrop','Balloon installation','Additional bakery items as a vendor pass-through','Event photographer']},
  {id:'cocoa',title:'Hot Cocoa Bar',cat:'Food & Beverage',tags:['food','seasonal'],dur:'Up to 1 hour',price:800,
   desc:'A winter cocoa station with mix-ins, insulated cups, and full setup.',
   inc:['Hot chocolate station with dairy and oat milk options','Mini marshmallows, whipped cream, and chocolate shavings','Peppermint stick stirrers','Insulated cups, lids, and napkins','Setup and basic event support'],
   add:["S'mores kit",'Hot cocoa bombs','Cookie pairing bar','Take-home mugs','Seasonal photo backdrop','Event attendant']}
];
